storybook.test.js causes test to fail (angular)
If storybook.test is a JS file, you will get the following error:

 FAIL  src/storybook.test.js
  ● Test suite failed to run
    Jest encountered an unexpected token
   ...
SyntaxError: Cannot use import statement outside a module

Saving the file as .ts (which is nice anyways in an angular project)